

CREATE TABLE  "USERS" 
   (	"USER_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(225) NOT NULL ENABLE, 
	"ACTIVE" NUMBER(1,0), 
	"STATUS" NUMBER(1,0), 
	"PASSWORD" VARCHAR2(100) NOT NULL ENABLE, 
	"DOB" VARCHAR2(25), 
	"GENDER" VARCHAR2(1), 
	"IMG" VARCHAR2(100), 
	 PRIMARY KEY ("USER_ID") ENABLE
   )
/




CREATE TABLE  "TRADER" 
   (	"TRADER_ID" NUMBER(8,0), 
	"TRADER_NAME" VARCHAR2(25), 
	"DESCRIPTION" VARCHAR2(3000), 
	"USER_ID" NUMBER(8,0), 
	"MOBILE" VARCHAR2(25), 
	"STATUS" NUMBER, 
	"PASSWORD" VARCHAR2(100), 
	 PRIMARY KEY ("TRADER_ID") ENABLE
   )
/
ALTER TABLE  "TRADER" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES  "USERS" ("USER_ID") ENABLE
/




CREATE TABLE  "SHOP" 
   (	"SHOP_ID" NUMBER(8,0), 
	"SHOP_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"SHOP_LOCATION" VARCHAR2(25) NOT NULL ENABLE, 
	"TRADER_ID" NUMBER(8,0), 
	"IMG" VARCHAR2(255), 
	 PRIMARY KEY ("SHOP_ID") ENABLE
   )
/
ALTER TABLE  "SHOP" ADD FOREIGN KEY ("TRADER_ID")
	  REFERENCES  "TRADER" ("TRADER_ID") ENABLE
/



CREATE TABLE  "PRODUCT_TYPE" 
   (	"PRODUCT_TYPE_ID" NUMBER(8,0), 
	"PRODUCT_TYPE_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"SHOP_ID" NUMBER(8,0), 
	"DESCRIPTION" VARCHAR2(3000), 
	 PRIMARY KEY ("PRODUCT_TYPE_ID") ENABLE
   )
/
ALTER TABLE  "PRODUCT_TYPE" ADD FOREIGN KEY ("SHOP_ID")
	  REFERENCES  "SHOP" ("SHOP_ID") ENABLE
/




CREATE TABLE  "PRODUCT" 
   (	"PRODUCT_ID" NUMBER(8,0), 
	"PRODUCT_NAME" VARCHAR2(25), 
	"DESCRIPTION" VARCHAR2(3000), 
	"PRICE" NUMBER(8,2), 
	"STOCK" NUMBER(8,0), 
	"MIN_ORDER" NUMBER(8,0), 
	"MAX_ORDER" NUMBER(8,0), 
	"PRODUCT_IMAGE" VARCHAR2(255), 
	"QUANTITY" NUMBER(8,0), 
	"ALLERGY_INFO" VARCHAR2(255), 
	"PRODUCT_TYPE_ID" NUMBER(8,0), 
	"ACTIVE" NUMBER, 
	 PRIMARY KEY ("PRODUCT_ID") ENABLE
   )
/
ALTER TABLE  "PRODUCT" ADD FOREIGN KEY ("PRODUCT_TYPE_ID")
	  REFERENCES  "PRODUCT_TYPE" ("PRODUCT_TYPE_ID") ENABLE

/
CREATE TABLE  "COLLECTION_SLOT" 
   (	"SLOT_ID" NUMBER(8,0), 
	"SLOT_DATE" VARCHAR2(25), 
	"AVAILABLE" NUMBER(8,0), 
	"SLOT_TIME" VARCHAR2(25), 
	 PRIMARY KEY ("SLOT_ID") ENABLE
   )
/



CREATE TABLE  "CART" 
   (	"CART_ID" NUMBER(8,0), 
	"USER_ID" NUMBER(8,0), 
	"PRODUCT_ID" NUMBER(8,0), 
	"QUANTITY" NUMBER, 
	 PRIMARY KEY ("CART_ID") ENABLE
   )
/
ALTER TABLE  "CART" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES  "USERS" ("USER_ID") ENABLE
/
ALTER TABLE  "CART" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES  "PRODUCT" ("PRODUCT_ID") ENABLE
/


CREATE TABLE  "DISCOUNT" 
   (	"DISCOUNT_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"PRICE" NUMBER(8,2), 
	"PRODUCT_TYPE_ID" NUMBER, 
	 PRIMARY KEY ("DISCOUNT_ID") ENABLE
   )
/
ALTER TABLE  "DISCOUNT" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES  "PRODUCT" ("PRODUCT_ID") ENABLE
/
ALTER TABLE  "DISCOUNT" ADD FOREIGN KEY ("PRODUCT_TYPE_ID")
	  REFERENCES  "PRODUCT_TYPE" ("PRODUCT_TYPE_ID") ENABLE
/




CREATE TABLE  "ORDERS" 
   (	"ORDER_ID" NUMBER(8,0), 
	"PRODUCT_ID" NUMBER(8,0), 
	"USER_ID" NUMBER(8,0), 
	"SLOT_ID" NUMBER(8,0), 
	"QUANTITY" NUMBER(8,0), 
	"STATUS" NUMBER, 
	 PRIMARY KEY ("ORDER_ID") ENABLE
   )
/
ALTER TABLE  "ORDERS" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES  "PRODUCT" ("PRODUCT_ID") ENABLE
/
ALTER TABLE  "ORDERS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES  "USERS" ("USER_ID") ENABLE
/
ALTER TABLE  "ORDERS" ADD FOREIGN KEY ("SLOT_ID")
	  REFERENCES  "COLLECTION_SLOT" ("SLOT_ID") ENABLE
/



CREATE TABLE  "PAYMENT" 
   (	"INVOICE_ID" NUMBER(8,0), 
	"USER_ID" NUMBER(8,0), 
	"PRICE" NUMBER(8,2), 
	 PRIMARY KEY ("INVOICE_ID") ENABLE
   )
/
ALTER TABLE  "PAYMENT" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES  "USERS" ("USER_ID") ENABLE
/



CREATE TABLE REVIEW (
	REVIEW_ID  NUMBER PRIMARY KEY,
	USER_ID  NUMBER REFERENCES USERS(USER_ID),
	VALUE  NUMBER,
	REVIEW  VARCHAR2(3000),
	PRODUCT_ID  NUMBER REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE OR REPLACE VIEW "TRADER_ORDERS" AS 
  SELECT orders.order_id, orders.user_id,product.product_image,product.product_id,product.product_name,product.price,trader.trader_id,orders.quantity,collection_slot.slot_id,collection_slot.slot_date,collection_slot.slot_time FROM 
collection_slot,orders,product,product_type,shop,trader
where 

collection_slot.slot_id =  orders.slot_id and
orders.product_id = product.product_id and product.product_type_id = product_type.product_type_id
and product_type.shop_id = shop.shop_id and shop.trader_id = trader.trader_id
/

CREATE OR REPLACE VIEW "TRADER_PRODUCTS" AS 
    SELECT TRADER.TRADER_ID, PRODUCT.PRODUCT_NAME, PRODUCT.PRODUCT_IMAGE, PRODUCT.QUANTITY, PRODUCT.PRICE
    FROM PRODUCT, DISCOUNT, PRODUCT_TYPE, SHOP, TRADER
    WHERE

    PRODUCT.PRODUCT_TYPE_ID = PRODUCT_TYPE.PRODUCT_TYPE_ID AND
    PRODUCT_TYPE.SHOP_ID = SHOP.SHOP_ID AND
    SHOP.TRADER_ID = TRADER.TRADER_ID



